package cluster

import (
	"bufio"
	"context"
	"fmt"
	"os/exec"
	"strings"
	"time"

	"github.com/thebanri/BanriFlow/pkg/analyzer"
	"github.com/tmc/langchaingo/llms"
)

// AutoFixStream takes the K8s error, asks the AI for a fixing bash command, executes it, and streams the process.
func AutoFixStream(ctx context.Context, provider, namespace, pod, errMsg, userInput string, w *bufio.Writer) {
	sendMsg := func(text string) {
		fmt.Fprintf(w, "data: %s\n\n", text)
		w.Flush()
	}

	actualPod := pod
	// Eğer kullanıcı aynı incident üzerinden peş peşe mesaj atıyorsa, önceki mesaj deployment'ı yamalamış ve eski pod silinmiş olabilir.
	// Bu yüzden her çağrıda prefix'ten yola çıkarak en güncel pod'u bulmaya çalışıyoruz.
	parts := strings.Split(pod, "-")
	var prefix string
	if len(parts) >= 3 {
		prefix = strings.Join(parts[:len(parts)-2], "-")
	} else {
		prefix = pod
	}

	findCmd := exec.CommandContext(ctx, "bash", "-c", fmt.Sprintf("kubectl get pods -n %s --no-headers | grep '^%s-' | head -n 1 | awk '{print $1}'", namespace, prefix))
	findOut, err := findCmd.CombinedOutput()
	foundPod := strings.TrimSpace(string(findOut))
	if err == nil && foundPod != "" && foundPod != pod {
		sendMsg(fmt.Sprintf("🔄 KubeSight: Eski pod (%s) artık yok. İşleme güncel pod (%s) üzerinden devam ediliyor.", pod, foundPod))
		actualPod = foundPod
	} else {
		sendMsg(fmt.Sprintf("🔄 Hedef Pod: %s/%s", namespace, actualPod))
	}

	if userInput != "" {
		sendMsg(fmt.Sprintf("🧑‍💻 Kullanıcı Talimatı İşleniyor: %s", userInput))
	} else {
		sendMsg("🧠 Yapay zeka sorunu analiz ediyor ve çözüm üretiyor...")
	}

	llm, err := analyzer.GetLLM(ctx, provider)
	if err != nil {
		sendMsg(fmt.Sprintf("❌ Hata: AI modeli yüklenemedi: %v", err))
		return
	}

	prompt := fmt.Sprintf(`You are a Kubernetes Automated Repair Assistant.
Your task is to produce EXACTLY ONE BASH/KUBECTL COMMAND to fix the given Kubernetes error.
OUTPUT ONLY THE COMMAND. Do not use markdown backticks, explanations, or any other text. JUST the raw command.

CRITICAL RULES:
1. NEVER use bash redirection operators like "<" or ">" (even as placeholders). Use dummy values if needed (e.g. dummy-user instead of <USER>).
2. NEVER use 'kubectl patch pod' or 'kubectl edit pod' on a running Pod! You cannot modify anything other than the 'image' on a live pod. To change commands, resources, or env vars, YOU MUST PATCH THE PARENT DEPLOYMENT.
   - WRONG: kubectl patch pod my-pod-1234 -p ...
   - CORRECT: kubectl patch deployment my-deployment -p ... (The exact deployment name is provided below).
3. UNSOLVABLE OR UNKNOWN ISSUES: If you are NOT 100%% sure how to fix the issue with a single patch/set command, DO NOT try to guess. Instead, output an 'echo' command advising the user what to check. 
   - NEVER output read-only commands like 'kubectl logs' or 'kubectl describe' as your final command!
   - ONLY output permanent fix commands (patch, set, apply) OR an 'echo' command with advice.
4. NAMESPACE REQUIREMENT: You MUST append '-n <Namespace>' to every kubectl command you generate.
5. CONTAINER NAME UNKNOWN: If you use 'kubectl set image' but don't know the exact container name, use '*' to target all containers. (e.g., kubectl set image deployment/app *=nginx:latest -n ns)
6. RESOURCE UPDATES: If you need to update CPU/Memory limits or requests, DO NOT use 'kubectl patch' because you might not know the exact container name, which will cause an error. Instead, ALWAYS use 'kubectl set resources'. (e.g., kubectl set resources deployment/app --requests=memory=256Mi -n ns)
7. FIXING COMMAND ERRORS: If the logs show a command error or the container is an empty busybox crashing instantly, you CAN fix it by patching the deployment command. Example: kubectl patch deployment <name> -n <ns> --type='json' -p='[{"op": "replace", "path": "/spec/template/spec/containers/0/command", "value": ["nginx", "-g", "daemon off;"]}]'
8. NO BAND-AID FIXES: DO NOT attempt to "fix" an application crash by simply replacing the container's command with a sleep command (e.g. 'sleep 3600' or 'tail -f /dev/null'). You MUST attempt to fix the root cause of the crash (e.g. patching volume mounts, securityContext, dnsPolicy, etc.). If you cannot determine the root cause, output an 'echo' command advising the user, do NOT sleep the container!
9. DO NOT ECHO THE ANALYSIS: The 'Background Analysis' below is just a hint generated by another system. DO NOT just echo this analysis back to the user! Your job is to use the attached logs and configs to ACTUALLY FIX the problem with a real 'kubectl patch' command!

Namespace: %s
Pod: %s
Deployment: %s
Background Analysis: %s`, namespace, actualPod, prefix, errMsg)

	// Try to fetch last 20 lines of logs to give AI more context
	// We check both current and previous (crashed) container logs
	logCmd := exec.CommandContext(ctx, "bash", "-c", fmt.Sprintf("kubectl logs %s -n %s --all-containers --tail=20 || kubectl logs %s -n %s --all-containers --tail=20 --previous", actualPod, namespace, actualPod, namespace))
	logOut, _ := logCmd.CombinedOutput()
	logStr := strings.TrimSpace(string(logOut))

	// Fetch pod's container commands and args to help diagnose CrashLoopBackOff when logs are empty
	cmdArgsCmd := exec.CommandContext(ctx, "kubectl", "get", "pod", actualPod, "-n", namespace, "-o", "jsonpath={range .spec.containers[*]}Container: {.name}\\nCommand: {.command}\\nArgs: {.args}\\n---\\n{end}")
	cmdArgsOut, _ := cmdArgsCmd.CombinedOutput()
	cmdArgsStr := strings.TrimSpace(string(cmdArgsOut))
	if len(cmdArgsStr) > 0 {
		prompt += fmt.Sprintf("\n\n--- POD CONTAINER CONFIGURATIONS ---\n%s\n---------------------------------", cmdArgsStr)
	}

	// Fetch full Deployment YAML to give AI visibility over dnsPolicy, securityContext, volumes, etc.
	yamlCmd := exec.CommandContext(ctx, "bash", "-c", fmt.Sprintf("kubectl get deployment %s -n %s -o yaml | grep -v 'f:' | grep -v 'kubectl.kubernetes.io/last-applied-configuration'", prefix, namespace))
	yamlOut, _ := yamlCmd.CombinedOutput()
	yamlStr := strings.TrimSpace(string(yamlOut))
	if len(yamlStr) > 0 {
		prompt += fmt.Sprintf("\n\n--- TARGET DEPLOYMENT YAML (Context for DNS, Volumes, Security) ---\n%s\n---------------------------------", yamlStr)
	}

	prompt += "\n\nCRITICAL NOTE: The user might ask you to 'check logs' or the error might be CrashLoopBackOff. DO NOT reply saying 'I cannot read logs'! The recent logs and container configurations have already been automatically fetched and are ATTACHED! READ THE LOGS AND CONFIGS to find the root cause (e.g. a typo in a sleep command), and directly output a 'kubectl patch deployment' command to fix it!"
	if len(logStr) > 0 {
		if len(logStr) < 2000 {
			prompt += fmt.Sprintf("\n\n--- INJECTED POD LOGS (Last 20 Lines) ---\n%s\n---------------------------------", logStr)
		} else {
			prompt += fmt.Sprintf("\n\n--- INJECTED POD LOGS (Last 20 Lines) ---\n%s\n---------------------------------", logStr[:2000]+" ...[TRUNCATED]")
		}
	} else {
		prompt += "\n\n--- INJECTED POD LOGS (Last 20 Lines) ---\n(Empty - Container crashed too fast to produce logs or pod was deleted. Rely on the POD CONTAINER CONFIGURATIONS above to spot mistakes like invalid sleep arguments!)\n---------------------------------"
	}

	if userInput != "" {
		prompt += fmt.Sprintf("\n\nEXPLICIT USER INSTRUCTION: %s\nYou MUST STRICTLY obey this user instruction! If they provide a solution or image name, use it directly without hesitation.", userInput)
	}

	prompt += "\n\nOutput ONLY the valid, safe bash command to execute."

	completion, err := llms.GenerateFromSinglePrompt(ctx, llm, prompt, llms.WithTemperature(0.1))
	if err != nil {
		sendMsg(fmt.Sprintf("❌ Hata: AI çözüm üretemedi: %v", err))
		return
	}

	cmdStr := strings.TrimSpace(completion)
	cmdStr = strings.ReplaceAll(cmdStr, "```bash", "")
	cmdStr = strings.ReplaceAll(cmdStr, "```", "")
	cmdStr = strings.TrimSpace(cmdStr)

	if cmdStr == "" {
		sendMsg("❌ AI herhangi bir komut önermedi.")
		return
	}

	sendMsg(fmt.Sprintf("⚙️ Çalıştırılan Komut: %s", cmdStr))
	time.Sleep(1 * time.Second) // Küçük bir bekleme efekti

	cmd := exec.CommandContext(ctx, "bash", "-c", cmdStr)
	out, err := cmd.CombinedOutput()

	if err != nil {
		sendMsg(fmt.Sprintf("⚠️ Komut başarısız oldu: %v", err))
		if len(out) > 0 {
			sendMsg(fmt.Sprintf("Çıktı: %s", string(out)))
		}
	} else {
		sendMsg("✅ Komut başarıyla uygulandı!")
		if len(out) > 0 {
			sendMsg(fmt.Sprintf("Çıktı: %s", string(out)))
		}

		if strings.HasPrefix(cmdStr, "echo") {
			sendMsg("ℹ️ Bu sorun doğrudan çözülemediği için (veya bilgi amaçlı) sadece öneri sunuldu.")
		} else {
			sendMsg("⏳ Değişikliklerin etki etmesi bekleniyor (5 saniye)...")
			time.Sleep(5 * time.Second)
			sendMsg("🔍 Durum doğrulanıyor...")

			checkCmd := exec.CommandContext(ctx, "kubectl", "get", "pod", actualPod, "-n", namespace, "-o", "jsonpath={.status.phase} {.status.containerStatuses[0].state.waiting.reason}")
			statusOut, checkErr := checkCmd.CombinedOutput()
			status := strings.TrimSpace(string(statusOut))

			if checkErr != nil {
				// If pod is deleted or not found, it means the deployment is rolling out a new pod.
				sendMsg("🎉 DOĞRULANDI: Eski pod silindi ve yenisi oluşturuluyor! (Deployment güncellendi)")
				sendMsg("[SOLVED]")
			} else if strings.Contains(status, "CrashLoopBackOff") || strings.Contains(status, "ImagePullBackOff") || strings.Contains(status, "ErrImagePull") {
				sendMsg("⚠️ KISMİ BAŞARI: Komut çalıştı ancak Pod hala hatalı. Mevcut durum: " + status)
			} else if strings.Contains(status, "Running") || strings.Contains(status, "Succeeded") || strings.Contains(status, "Pending") {
				// Pending is fine for now, it means it's starting. Running without CrashLoop is also fine.
				sendMsg("🎉 DOĞRULANDI: Sorun çözüldü veya çözülüyor! Pod durumu: " + status)
				sendMsg("[SOLVED]")
			} else {
				sendMsg("⚠️ DOĞRULAMA BELİRSİZ: Mevcut durum: " + status)
			}
		}
	}
	
	sendMsg("🏁 Süreç tamamlandı.")
	sendMsg("[DONE]")
}
