package cluster

import (
	"bufio"
	"context"
	"fmt"
	"os/exec"
	"strings"
	"time"

	"github.com/thebanri/BanriFlow/pkg/analyzer"
	"github.com/tmc/langchaingo/llms"
)

// AutoFixStream takes the K8s error, asks the AI for a fixing bash command, executes it, and streams the process.
func AutoFixStream(ctx context.Context, provider, namespace, pod, errMsg, userInput string, w *bufio.Writer) {
	sendMsg := func(text string) {
		fmt.Fprintf(w, "data: %s\n\n", text)
		w.Flush()
	}

	actualPod := pod
	parts := strings.Split(pod, "-")
	var prefix string
	if len(parts) >= 3 {
		prefix = strings.Join(parts[:len(parts)-2], "-")
	} else {
		prefix = pod
	}

	llm, err := analyzer.GetLLM(ctx, provider)
	if err != nil {
		sendMsg(fmt.Sprintf("❌ Hata: AI modeli yüklenemedi: %v", err))
		return
	}

	maxRetries := 3
	previousAttempts := ""

	for attempt := 1; attempt <= maxRetries; attempt++ {
		// En güncel pod'u bul
		findCmd := exec.CommandContext(ctx, "bash", "-c", fmt.Sprintf("kubectl get pods -n %s --sort-by=.metadata.creationTimestamp --no-headers | grep '^%s-' | tail -n 1 | awk '{print $1}'", namespace, prefix))
		findOut, err := findCmd.CombinedOutput()
		foundPod := strings.TrimSpace(string(findOut))
		if err == nil && foundPod != "" && foundPod != actualPod {
			sendMsg(fmt.Sprintf("🔄 KubeSight: İşleme en güncel pod (%s) üzerinden devam ediliyor.", foundPod))
			actualPod = foundPod
		} else if attempt == 1 {
			sendMsg(fmt.Sprintf("🔄 Hedef Pod: %s/%s", namespace, actualPod))
		}

		if attempt > 1 {
			sendMsg(fmt.Sprintf("⚠️ Yapay Zeka pes etmiyor! %d. deneme başlatılıyor...", attempt))
		} else if userInput != "" {
			sendMsg(fmt.Sprintf("🧑‍💻 Kullanıcı Talimatı İşleniyor: %s", userInput))
		} else {
			sendMsg("🧠 Yapay zeka sorunu analiz ediyor ve çözüm üretiyor...")
		}

		prompt := fmt.Sprintf(`You are a Kubernetes Automated Repair Assistant.
Your task is to produce EXACTLY ONE BASH/KUBECTL COMMAND to fix the given Kubernetes error.
OUTPUT ONLY THE COMMAND. Do not use markdown backticks, explanations, or any other text. JUST the raw command.

CRITICAL RULES:
1. NEVER use bash redirection operators like "<" or ">" (even as placeholders). If you need to create resources, use 'kubectl create ...' commands instead of 'echo ... | kubectl apply -f -'.
2. NEVER use 'kubectl patch pod' or 'kubectl edit pod' on a running Pod! To change commands, resources, or env vars, YOU MUST PATCH THE PARENT DEPLOYMENT.
   - However, if the crash is caused by invalid content inside a ConfigMap, you MUST fix the ConfigMap directly using 'kubectl patch configmap' or 'kubectl create configmap ... --dry-run=client -o yaml | kubectl apply -f -'.
3. MULTIPLE COMMANDS: You ARE ALLOWED to output multiple commands chained with '&&' or ';'. For example, if you need to fix an RBAC issue, you MUST create the Role and RoleBinding using 'kubectl create role ... && kubectl create rolebinding ...'. DO NOT give up and output an 'echo' command!
4. NAMESPACE REQUIREMENT: You MUST append '-n <Namespace>' to every kubectl command you generate.
5. CONTAINER NAME UNKNOWN: If you use 'kubectl set image' but don't know the exact container name, use '*' to target all containers. (e.g., kubectl set image deployment/app *=nginx:latest -n ns)
6. RESOURCE UPDATES: If you need to update CPU/Memory limits, ALWAYS use 'kubectl set resources'. (e.g., kubectl set resources deployment/app --requests=memory=256Mi -n ns)
7. FIXING COMMAND ERRORS: If the logs show a command error, you CAN fix it by patching the deployment command. Example: kubectl patch deployment <name> -n <ns> --type='json' -p='[{"op": "replace", "path": "/spec/template/spec/containers/0/command", "value": ["nginx", "-g", "daemon off;"]}]'
8. NO BAND-AID FIXES: DO NOT attempt to "fix" an application crash by simply replacing the container's command with arbitrary sleeping commands or endless loops. You MUST attempt to fix the root cause of the crash (e.g. patching volume mounts, securityContext, dnsPolicy, etc.).
9. DO NOT ECHO THE ANALYSIS: The 'Background Analysis' below is just a hint generated by another system. DO NOT just echo this analysis back to the user! Your job is to use the attached logs and configs to ACTUALLY FIX the problem with real 'kubectl' commands!

Namespace: %s
Pod: %s
Deployment: %s
Background Analysis: %s`, namespace, actualPod, prefix, errMsg)

		if previousAttempts != "" {
			prompt += fmt.Sprintf("\n\nCRITICAL WARNING: YOUR PREVIOUS FIX ATTEMPTS FAILED!\nThe pod is still crashing. You must LEARN from your previous mistakes and try a DIFFERENT JSON PATCH OR APPROACH!\nHere is what you already tried:\n%s", previousAttempts)
		}

		logCmd := exec.CommandContext(ctx, "bash", "-c", fmt.Sprintf("kubectl logs %s -n %s --all-containers --tail=20 || kubectl logs %s -n %s --all-containers --tail=20 --previous", actualPod, namespace, actualPod, namespace))
		logOut, _ := logCmd.CombinedOutput()
		logStr := strings.TrimSpace(string(logOut))

		eventCmd := exec.CommandContext(ctx, "bash", "-c", fmt.Sprintf("kubectl get events -n %s --field-selector involvedObject.name=%s --sort-by='.lastTimestamp' | tail -n 5", namespace, actualPod))
		eventOut, _ := eventCmd.CombinedOutput()
		eventStr := strings.TrimSpace(string(eventOut))
		if len(eventStr) > 0 && !strings.Contains(eventStr, "No resources found") {
			prompt += fmt.Sprintf("\n\n--- POD KUBERNETES EVENTS (CRITICAL for Mount/Pull/Schedule Errors) ---\n%s\n---------------------------------", eventStr)
		}

		cmdArgsCmd := exec.CommandContext(ctx, "kubectl", "get", "pod", actualPod, "-n", namespace, "-o", "jsonpath={range .spec.containers[*]}Container: {.name}\\nCommand: {.command}\\nArgs: {.args}\\n---\\n{end}")
		cmdArgsOut, _ := cmdArgsCmd.CombinedOutput()
		cmdArgsStr := strings.TrimSpace(string(cmdArgsOut))
		if len(cmdArgsStr) > 0 {
			prompt += fmt.Sprintf("\n\n--- POD CONTAINER CONFIGURATIONS ---\n%s\n---------------------------------", cmdArgsStr)
		}

		yamlCmd := exec.CommandContext(ctx, "bash", "-c", fmt.Sprintf("kubectl get deployment %s -n %s -o yaml | grep -v 'f:' | grep -v 'kubectl.kubernetes.io/last-applied-configuration'", prefix, namespace))
		yamlOut, _ := yamlCmd.CombinedOutput()
		yamlStr := strings.TrimSpace(string(yamlOut))
		if len(yamlStr) > 0 {
			prompt += fmt.Sprintf("\n\n--- TARGET DEPLOYMENT YAML (Context for DNS, Volumes, Security) ---\n%s\n---------------------------------", yamlStr)
		}

		prompt += "\n\nCRITICAL NOTE: The user might ask you to 'check logs' or the error might be CrashLoopBackOff. DO NOT reply saying 'I cannot read logs'! The recent logs and container configurations have already been automatically fetched and are ATTACHED! READ THE LOGS AND CONFIGS to find the root cause, and directly output a 'kubectl patch deployment' command to fix it!"
		
		if len(logStr) > 0 {
			if len(logStr) < 2000 {
				prompt += fmt.Sprintf("\n\n--- INJECTED POD LOGS (Last 20 Lines) ---\n%s\n---------------------------------", logStr)
			} else {
				prompt += fmt.Sprintf("\n\n--- INJECTED POD LOGS (Last 20 Lines) ---\n%s\n---------------------------------", logStr[:2000]+" ...[TRUNCATED]")
			}
		} else {
			prompt += "\n\n--- INJECTED POD LOGS (Last 20 Lines) ---\n(Empty - Container crashed too fast to produce logs or pod was deleted. Rely on the POD CONTAINER CONFIGURATIONS above to spot mistakes!)\n---------------------------------"
		}

		if userInput != "" {
			prompt += fmt.Sprintf("\n\nEXPLICIT USER INSTRUCTION: %s\nYou MUST STRICTLY obey this user instruction! If they provide a solution or image name, use it directly without hesitation.", userInput)
		}

		prompt += "\n\nOutput ONLY the valid, safe bash command to execute."

		completion, err := llms.GenerateFromSinglePrompt(ctx, llm, prompt, llms.WithTemperature(0.2))
		if err != nil {
			sendMsg(fmt.Sprintf("❌ Hata: AI çözüm üretemedi: %v", err))
			return
		}

		cmdStr := strings.TrimSpace(completion)
		cmdStr = strings.ReplaceAll(cmdStr, "```bash", "")
		cmdStr = strings.ReplaceAll(cmdStr, "```", "")
		cmdStr = strings.TrimSpace(cmdStr)

		if cmdStr == "" {
			sendMsg("❌ AI herhangi bir komut önermedi.")
			return
		}

		sendMsg(fmt.Sprintf("⚙️ Çalıştırılan Komut: %s", cmdStr))
		time.Sleep(1 * time.Second)

		cmd := exec.CommandContext(ctx, "bash", "-c", cmdStr)
		out, err := cmd.CombinedOutput()

		if err != nil {
			sendMsg(fmt.Sprintf("⚠️ Komut başarısız oldu: %v", err))
			if len(out) > 0 {
				sendMsg(fmt.Sprintf("Çıktı: %s", string(out)))
			}
			previousAttempts += fmt.Sprintf("- Attempt %d: %s (Failed execution: %v)\n", attempt, cmdStr, err)
			continue
		} else {
			sendMsg("✅ Komut başarıyla uygulandı!")
			if len(out) > 0 {
				sendMsg(fmt.Sprintf("Çıktı: %s", string(out)))
			}

			if strings.HasPrefix(cmdStr, "echo") {
				sendMsg("ℹ️ Bu sorun doğrudan çözülemediği için (veya bilgi amaçlı) sadece öneri sunuldu.")
				break
			} else {
				sendMsg("⏳ Değişikliklerin etki etmesi bekleniyor (10 saniye)...")
				time.Sleep(10 * time.Second)
				sendMsg("🔍 Durum doğrulanıyor...")

				findCmd2 := exec.CommandContext(ctx, "bash", "-c", fmt.Sprintf("kubectl get pods -n %s --sort-by=.metadata.creationTimestamp --no-headers | grep '^%s-' | tail -n 1 | awk '{print $1}'", namespace, prefix))
				findOut2, _ := findCmd2.CombinedOutput()
				newestPod := strings.TrimSpace(string(findOut2))
				if newestPod != "" {
					actualPod = newestPod
				}

				checkCmd := exec.CommandContext(ctx, "kubectl", "get", "pod", actualPod, "-n", namespace, "-o", "jsonpath={.status.phase} {.status.containerStatuses[0].state.waiting.reason} Ready:{.status.containerStatuses[0].ready}")
				statusOut, checkErr := checkCmd.CombinedOutput()
				status := strings.TrimSpace(string(statusOut))

				if checkErr != nil {
					sendMsg("🎉 DOĞRULANDI: Eski pod silindi ve yenisi oluşturuluyor! (Deployment güncellendi)")
					sendMsg("[SOLVED]")
					break
				} else if strings.Contains(status, "CrashLoopBackOff") || strings.Contains(status, "ImagePullBackOff") || strings.Contains(status, "ErrImagePull") || strings.Contains(status, "RunContainerError") || strings.Contains(status, "ContainerCreating") || strings.Contains(status, "CreateContainerConfigError") || strings.Contains(status, "Pending") {
					if attempt < maxRetries {
						sendMsg("⚠️ KISMİ BAŞARI: Komut çalıştı ancak yeni Pod hala hatalı veya askıda (Pending). Durum: " + status)
						previousAttempts += fmt.Sprintf("- Attempt %d: %s (Result: %s)\n", attempt, cmdStr, status)
					} else {
						sendMsg("❌ BAŞARISIZ: Maksimum deneme sayısına ulaşıldı. Pod hala hatalı. Durum: " + status)
					}
				} else if strings.Contains(status, "Running") || strings.Contains(status, "Succeeded") {
					if strings.Contains(status, "Ready:false") {
						if attempt < maxRetries {
							sendMsg("⚠️ KISMİ BAŞARI: Pod çalışıyor (Running) ancak henüz Hazır (Ready) değil. Readiness Probe hatası olabilir. Durum: " + status)
							previousAttempts += fmt.Sprintf("- Attempt %d: %s (Result: %s - Pod is Running but Not Ready)\n", attempt, cmdStr, status)
						} else {
							sendMsg("❌ BAŞARISIZ: Maksimum deneme sayısına ulaşıldı. Pod çalışıyor ama Hazır (Ready) değil. Durum: " + status)
						}
					} else {
						sendMsg("🎉 DOĞRULANDI: Sorun çözüldü! Pod durumu: " + status)
						sendMsg("[SOLVED]")
						break
					}
				} else {
					sendMsg("⚠️ DOĞRULAMA BELİRSİZ: Mevcut durum: " + status)
					break
				}
			}
		}
	}
	sendMsg("🏁 Süreç tamamlandı.")
	sendMsg("[DONE]")
}
